### ISSUE TITLE
Fatal error - Vendor missing

### ISSUE THREAD

**Issue by Dinocanid** [mysidia-deluxe/Mysidia-Deluxe#6]
This message appears when attempting to visit any page:

`Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\Mysidia-Deluxe/vendor/autoload.php' (include_path='.;C:\php\pear') in C:\xampp\htdocs\Mysidia-Deluxe\bootstrap.php on line 5`

The vendor directory doesn't exist in the files, and neither does autoload.php.

**Comment by awjudd** [comment]
You need to run a `composer install` from the folder which contains the `composer.json` file.  The plan for releases would be to include the vendor folder in the final release.

**Comment by Dinocanid** [comment]
Can you include it? Composer fails to install on my end.

**Comment by awjudd** [comment]
It is a bad practice to include it in your repository.  What is the error you are getting on your end?

**Comment by Dinocanid** [comment]
Can you explain how? Would it allow people to install random extensions?

This is the error I get:

`The PHP exe file you specified did not run correctly:
C:\xampp\php\php.exe

The php.ini used by your command-line PHP is: C:\xampp\php\php.ini

A setting in your php.ini could be causing the problem: Either the 'extension_dir' value is incorrect or the dll does not exist.

Program Output:
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_imagick.dll' - The specified module could not be found.
 in Unknown on line 0`

**Comment by awjudd** [comment]
That's just a warning it shouldn't cause any issues.

**Comment by Dinocanid** [comment]
But...it is lol. It's not letting me continue the installation.
Do you have instructions on installing with the `.phar` file?

(also I still think it should be included in the repo, for the sake of easing up the work on any future contributors)

**Comment by awjudd** [comment]
It should never be included in the repository.  That is a bad pattern to follow.  Only include it in the releases because that is the end-user ready state.

**Comment by Dinocanid** [comment]
Ok but..._why_ is it a bad pattern to follow?

**Comment by awjudd** [comment]
You want to keep your repository as light as possible.  There is no reason to commit other peoples code.  Composer's site gives a good explanation.
https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

**Comment by awjudd** [comment]
I haven't set Composer up on a Windows machine before.  It should just be the same - try to watch YouTube videos?
